spring:
  application:
    name: todo

  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: nofy
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true